name: Update PSL Data

on:
  schedule:
    - cron: '0 16 * * 6'  # Runs at 16:00 on Saturdays
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run the script
      run: python main.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'groundcat'
        git config --global user.email '11240246+groundcat@users.noreply.github.com'
        git add public_suffix_list*.json
        git commit -m 'Update PSL data [skip ci]'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 